version = 1

[[steps]]
plugin = 'link'
regex  = true

[steps.links]
'.*/(.*)\.configsymlink' = '~/.config/\1' # Any file/folder ending in .configsymlink goes in ~/.config
'.*/(.*)\.symlink'       = '~/.\1'        # Any file/folder ending in .symlink goes in home directory (hidden)

[[steps]]
plugin        = 'shell'
pre-condition = '! which brew >/dev/null 2>&1'

[steps.commands]
'Installing Homebrew'          = '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
'Adding HomeBrew to the shell' = '''echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile'''

[[steps]]
plugin = 'shell'

[steps.commands]
'Set macOS config'          = './macos/defaults.sh'
'Install Homebrew packages' = 'brew bundle --no-upgrade --file=./packages/Brewfile'
'Install Mise packages'     = 'mise install'

[[steps]]
plugin = 'shell'
pre-condition = 'test -f ./packages/Brewfile.$(uname -n | cut -d. -f1)'

[steps.commands]
'Install device-specific Homebrew packages'  = 'brew bundle --no-upgrade --file=./packages/Brewfile.$(uname -n | cut -d. -f1)'

[[steps]]
plugin = 'shell'
pre-condition = '! grep xonsh /etc/shells >/dev/null 2>&1'

[steps.commands]
'Set xonsh as default shell'  = './xonsh/set-default.sh'