[tools]
go     = "1.26"
node   = "24.15"
python = "3.14"

[settings]
experimental                        = true
idiomatic_version_file_enable_tools = ["python", "node"]

[settings.python]
uv_venv_auto = true
