#!/bin/bash
#
# Pretty log showing the changed files.
#
# Author: @holman
#

HASH="%C(yellow)%h%Creset"
RELATIVE_TIME="%Cgreen<%ar>%Creset"
AUTHOR="%C(blue)[%cn]%Creset"
REFS="%C(red)%d%Creset"
SUBJECT="%s"

FORMAT="$HASH $SUBJECT $AUTHOR $RELATIVE_TIME $REFS"

git log --pretty=format:"${FORMAT}" $* --decorate --numstat |
    less -FXRS
