model = "gpt-5.2-codex"
model_reasoning_effort = "high"
personality = "pragmatic"

[projects."/Users/igalarzab/Developer/personal"]
trust_level = "trusted"

[mcp_servers.playwright]
args = ["@playwright/mcp@latest"]
command = "npx"
