---

apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  type: NodePort
  selector:
    app: home-assistant
  ports:
    - name: http
      protocol: TCP
      port: 8123
      targetPort: 8123
      nodePort: 8123

